urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

# Comment the next two lines to disable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('movies.views',
    url(r'^movies/$',                'index',  name='movie_index'),
    url(r'^movies/(?P<slug>.*)/$',   'detail', name='detail'),
    url(r'^scenes/$',                'sceneList',  name='sceneList'),
    url(r'^scenes/(?P<sha256>.*)/$', 'sceneDetail', name='sceneDetail'),
)

urlpatterns += patterns('user.view',
    url(r'^$',             direct_to_template, {'template' : 'user/login.html'}),
    url(r'^user/$',        'index',       name='user_index'),
    url(r'^dbLogin$',      'dbLogin',     name='dbLogin'),
    url(r'^user/logout/$', 'dbLogout',    name='dbLogout'),
)

urlpatterns += patterns('general.views',
    url(r'^search/$',         login_required(direct_to_template), {'template' : 'general/simpleSearch.html'}),
    url(r'^simpleSearch/$',   'simpleSearch',     name='simpleSearch'),
    url(r'^esearch/$',        'eSearchView',      name='eSearchView'),
    url(r'^extendedSearch/$', 'extendedSearch',   name='extendedSearch'),
)

urlpatterns += patterns('actors.views',
    url(r'^actors/$',                       direct_to_template, {'template' : 'actor/actorList.html'}, name='actors'),
    url(r'^actors/actors_(?P<letter>.*)/$', 'actors'),
    url(r'^actors/(?P<slug>.*)/$',          'detail', name='actor_detail'),
)

urlpatterns += patterns('genres.views',
    url(r'^genres/$',                       'genres', name='genres'),
    url(r'^genres/(?P<slug>.*)/$',          'detail', name='genre_detail'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 'django.views.static.serve', document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, 'django.contrib.staticfiles.views.serve', document_root=settings.STATIC_ROOT)

actors/models.py
from django.db import models

class Person(models.Model):
    GenderChoice = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other')
    )

    firstName = models.CharField(max_length=100)
    lastName  = models.CharField(max_length=100)
    picture   = models.ImageField(upload_to='images/person/portrait/', blank=True, null=True)
    gender    = models.CharField(max_length=1, choices=GenderChoice, default='o')
    description = models.CharField(max_length=500, blank=True, null=True)
    alternativeNames = models.TextField(blank=True, null=True)
    birthday  = models.DateField(blank=True, null=True)
    ethnicity = models.CharField(max_length=20, blank=True, null=True)
    detailedInformation = models.TextField(blank=True, null=True)
    link = models.URLField(blank=True, null=True)

    def __unicode__(self):
        return self.firstName + " " + self.lastName

    def getFullName(self):
        return self.firstName + " " + self.lastName

class Actor(models.Model):
    id = models.AutoField(primary_key=True)
    person = models.ForeignKey(Person)
    scenes = models.ManyToManyField('movies.Scene', blank=True, null=True)

    @models.permalink
    def getAbsoluteUrl(self):
        return ('detail', (self.id,))

    def __unicode__(self):
        return str(self.id) + ": " + self.person.firstName + " " + self.person.lastName

genres/models.py
from django.db import models

class Genre(models.Model):
    shortDescription = models.CharField(max_length=50, unique=True, blank=False, null=False)
    slug             = models.SlugField(max_length=50)
    longDescription  = models.TextField(blank=True, null=True)
    scenes           = models.ManyToManyField('movies.Scene', blank=True, null=True)

    def __unicode__(self):
        return self.shortDescription

movies/models.py
from django.db import models
from actors.models import Actor
from genres.models import Genre

class Movie(models.Model):
    class Meta:
        permissions = (
            ("watch", "Can watch movielist, movie details and scenes"),
            ("allowedRestricted", "Can watch restriced scenes")
        )
    title = models.CharField(max_length=500, unique=True)
    slug = models.SlugField(max_length=200)
    description = models.TextField(blank=True, null=True)
    productionDate = models.DateField(blank=True, null=True)
    frontCover = models.ImageField(upload_to='images/movies/', blank=True, null=True)
    backCover = models.ImageField(upload_to='images/movies/', blank=True, null=True)
    restrictedView = models.BooleanField(default=False)

    @models.permalink
    def get_absolute_url(self):
        return ('detail', (self.slug,))

    def __unicode__(self):
        return self.title

class Scene(models.Model):
    class Meta:
        permissions = (
            ("watch", "Can watch movielist, movie details and scenes"),
            ("allowedRestricted", "Can watch restriced scenes")
        )
    sha256 = models.CharField(max_length=64, null=False, unique=True)
    movie = models.ForeignKey(Movie)
    title = models.CharField(max_length=500)
    animatedImage = models.CharField(max_length=500, blank=True, null=True)
    stillImage = models.CharField(max_length=500, blank=True, null=True)
    sceneRelPath = models.CharField(max_length=500, blank=True, null=True)
    duration = models.IntegerField()
    restrictedView = models.BooleanField(default=False)
    description = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.sha256

    def getAllActors(self):
        return Actor.objects.filter(scenes=self)

    def getAllGenres(self):
        return Genre.object.filter(scenes=self)

movies/views.py
import os
from django.template import RequestContext, loader
from django.conf import settings
from movies.models import Movie, Scene
from directors.models import Director
from actors.models import Actor
from genres.models import Genre
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import permission_required

@permission_required('movies.watch', login_url="/")
def index(request):
    if request.user.has_perm('movies.allowedRestricted'):
        allMovies = Movie.objects.all().order_by('title')
    else:
        allMovies = Movie.objects.filter(restrictedView=False)

    template = loader.get_template('movie/movieList.html')
    context = RequestContext(request, {
        'movies': allMovies,
    })

    return HttpResponse(template.render(context))

def __isSupportedPlaybackFormat(scene):
    if len(scene.sceneRelPath) <= 0: return False
    extension = os.path.splitext(scene.sceneRelPath)[1]

    if extension.lower() in settings.PLAYER_SUPPORTED_FORMATS:
        return True

    return False

def __getDurationFromScenes(scenes):
    durationOfAllScenes = 0
    for scene in scenes:
        durationOfAllScenes += scene.duration
    return durationOfAllScenes

@permission_required('movies.watch', login_url="/")
def detail(request, slug):
    user = request.user
    movie = get_object_or_404(Movie, slug=slug)
    if movie.restrictedView and not user.has_perm('movies.allowedRestricted'):
        return render_to_response('movie/restrictedMovie.html')

    directors = Director.objects.filter(movies=movie)

    scenes = Scene.objects.filter(movie=movie).order_by('title')

    movie.directors = directors
    movie.studio = "STUDIOTODO"
    movie.actors = Actor.objects.filter(scenes__in=scenes).distinct()
    movie.genres = Genre.objects.filter(scenes__in=scenes).distinct()
    duration = __getDurationFromScenes(scenes)

    context = RequestContext(request, {
        'movie'  : movie,
        'scenes' : scenes,
        'movieDuration': duration,
        'mediaBasePath' : settings.MOVIE_BASE_DIR
    })

    return render_to_response('movie/movieDetail.html', context)

@permission_required('movies.watch', login_url="/")
def sceneList(request):
    scenes = Scene.objects.all().order_by('title')
    context = RequestContext(request, {
        'scenes': scenes,
    })

    return render_to_response('scene/sceneList.html', context)

@permission_required('movies.watch', login_url="/")
def sceneDetail(request, sha256):
    scene = get_object_or_404(Scene, sha256=sha256)
    context = RequestContext(request, {
        'scene' : scene,
        'mediaBasePath' : settings.MOVIE_BASE_DIR
    })

    return render_to_response('scene/sceneDetail.html', context)

movies/templates/scene/_sceneListTable.html
{% load scene_extras %}

<table class="scenesTable">
    <tr class="header" align="left"><th>Preview</th> <th>Title</th> <th>Actors</th> <th>Genres</th></tr>
    {% for scene in scenes %}
        {% if scene|allowedToView:user %}
            <tr class="scene">
                <td class="animatedGif">
                    <a href="/scenes/{{ scene.sha256 }}">
                        {% if movie.backCover %}
                            <img src="{{ scene.stillImage }}" onmouseover="{{ scene.animatedImage }}" width="200" height="160" alt="{{ scene.title }}">
                        {% else %}
                            <img src="{{ STATIC_URL }}/img/x.png" width="200" height="160" alt="{{ scene.title }}">
                        {% endif %}
                    </a>
                </td>

                <td>{{ scene.title }}</td>

                <td class="actors">
                    {% if scene.actor_set.all %}
                        {% for actor in scene.actor_set.all %}
                            <a href="/actors/{{ actor.id }}/">{{ actor.person.getFullName }}</a>,
                        {% endfor %}
                    {% else %}
                        -
                    {% endif %}
                </td>

                <td class="genres">
                    {% if scene.genre_set.all %}
                        {% for genre in scene.genre_set.all %}
                            <a href="/genres/{{ genre.slug }}/">{{ genre.shortDescription }}</a>,
                        {% endfor %}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endif %}
    {% endfor %}
</table>

movies/templates/scene/sceneDetail.html
{% extends "base.html" %}
{% load scene_extras general_extras %}

{% block title %}{{ scene.title }}{% endblock %}

{% block content %}
    <table class="sceneDetail">
        <tr class="title" align="left"><th colspan="2">{{ scene.title }}</th></tr>

        <tr class="video" align="left">
            <td colspan="2">
                {% if scene.sceneRelPath %}
                    {% if scene.supportedFormat %}
                        <div id="videoPlayer">
                            <p id="container1">Please install the Flash Plugin</p>
                            <script type="text/javascript">
                                var flashvars = { file:'{{ mediaBasePath }}/{{ scene.sceneRelPath }}',autostart:'false' };
                                var params = { allowfullscreen:'true', allowscriptaccess:'always' };
                                var attributes = { id:'playerID', name:'playerName' };
                                swfobject.embedSWF('{{ STATIC_URL }}/js/vendor/player.swf','container1','240','135','9.0.115','false', flashvars, params, attributes);
                            </script>
                        </div>
                    {% else %}
                        Movie format not supported.
                    {% endif %}
                {% else %}
                    <img src="{{ STATIC_URL }}/img/x.png" width="200" height="160" alt="{{ scene.title }}">
                {% endif %}
            </td>
        </tr>

        <tr><td align="center" colspan="2">Video Data</td></tr>

        <tr>
            <td>Runtime:</td>
            <td>{{ scene.duration|durationToString }}</td>
        </tr>

        <tr>
            <td>Movie:</td>
            <td><a href="{{ scene.movie.get_absolute_url }}">{{ scene.movie.title }}</a></td>
        </tr>

        <tr>
            <td>Description:</td>
            <td>{{ scene.description|setValue }}</td>
        </tr>

        <tr>
            <td>Genres:</td>
            <td>
                {% if scene.genre_set.all %}
                    {% for genre in scene.genre_set.all %}
                        <a href="/genres/{{ genre.slug }}/">{{ genre.shortDescription }}</a>,
                    {% endfor %}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>

        <tr>
            <td>Actors:</td>
            <td>
                {% if scene.actor_set.all %}
                    {% for actor in scene.actor_set.all %}
                        <a href="/actors/{{ actor.id }}">{{ actor.person.getFullName }}</a>,
                    {% endfor %}
                {% else %}
                    -
                {% endif %}
            </td>
        </tr>
    </table>
{% endblock %}

movies/templates/scene/sceneList.html
{% extends "base.html" %}

{% block title %}Scene list{% endblock %}

{% block content %}

{% if scenes %}
    <div class="scenes">
        {% include "scene/_sceneListTable.html" with scenes=scenes %}
    </div>
{% else %}
    {% if error %}
        <p class="error">{{ error }}</p>
    {% else %}
        <p class="error">No Scenes found.</p>
    {% endif %}
{% endif %}

{% endblock %}